apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ibm-entitled-registry-credentials
  namespace: ci
spec:
  encryptedData:
    IBM_ENTITLED_REGISTRY_PASSWORD: AgBTIpHHaF/pggm6OSCi7RJDQF21jOO7IFMc3BL6lVU4+mAc+vjEhUNiQoqDztj/TooerDlN5f2qLXqervsBMX5HAdhOpe6ZmXXPBHo8TZEYgSEJuG+glTsqxLgLeIENnHRxKXiUAOqZRpbRQGXluZl4zh85etjDyihQNIEdEuKx1MzwW04NKUM59zeNOehbEiph9kVqtdjNeEULktG9dLWHFATT3xDn5Wb/iInPFGSwsuJ+aWU3mn4WtxF3m2Z5o1Y9gMNiztG60CuAx/2gEsuLvSgDNj1K/YnrDdZE+nBH6HLZmR71dqWGtFs+Gaj/2FL1CmzQiq6nhCzV1qi1bDKttejAOQMSrlpFI3y2aXEiwXF+l5j/4uFEHEcfQTPOaJcCnjZBv4K9c+1j8AfKlKA9FeHOxDpfbaeXWTKfLwWEJK4ZftOYMh7hViK0tJoT8zyat+pH6lQpiGo7eMXcRDcKNj45glsXChf90NX+LWOLloZeKyBAE7nngz5GCQkorEr8ds8FzZwF8tIkUbVSQG/Ofdt2Ji/ex1lMd3mQ36JnNYhWm3Z0J8M5JWgwm823T7DmzCHP6QZHSF5DItdk2+cQum3kA+znhwIU7Pgv64ukpbfl3SXAa3iV723K1yl8HpijXNlnMPodjOZnbvj63KZ98l7UKbcgj1yOT4lqkEB4Vlc3o0UM4WlWAv1xSmOzF/JI/4Gq3fSosAmzqYASi2jcQBJqvZtv8/59uhDrVIixxWCXKEAR+LchZ7z4655RrAHJeFbLMHP2Rjqu2Gx2ONWhxuvs37PHVTqt4e+BjC98aXApS2wnznJ2x4UtraxivL2N6IE6xQ6b4nLoyfj6L/gwJCh3AQbVXCU+NrmfBmSWZYIOoZHZcCPaQB6Ok+2xucpNPODneIsHgIAd/Fx7dijzW3+F5drhL8gMccVc8ys5OAEFDYXAMS2P082egUlO4O4=
    IBM_ENTITLED_REGISTRY_USER: AgA+zo17wASRXok12KqY5OHLlUw5tb6U0JbL7lugF+FtIK8sgs9OYSVvmqanWFyLYuWM2fCfdjq9x22IrSAHIcUuPr5A8BwrMVFZed+drqxN1Jy/yO55OGFoATgvFVHWE7BCorTumO1vmxGju//Uj/36fYyr8ncExxP/JroM0JhvGruxaysXR7lOoZ9FRTRY1vhfL97A2oIE1YmDegptIlAuwniE7KwI3w6HGcnD8JzPErZpWICWzu4W/6+TUKpu3cTn6XnbAsqklkoLTrXHijM0c3DqiIr4RbyijR8tQZRaj2UYgw/w1bfy9ecPZ10AUN0/sgD1OL1IPvDxPHVJGOhBINhK6JXClX//dsVYc0HmAxHl1pE+Puw3WyV7UDDywTCPb88gH2o9o+9kFueQNh0QtwyBbD4N9CDo/ASqKW6OMqFs34NQGqW0s5ZT2tUhGHY6EMe3gcv/WAqtq+Fps43WyD9tFSgNE0L+LDXt70wXJXaTmQvzmMhmjFkes9usdhOr9Eb6uJz7N/iAeTnANKAvJLIs7Gh9m9W3dM8IZcXTSDfdXzrUhNNo/gQhcaSSseON6WAjmLEKaeUdILPCitBc1PZ90+4NVYw95S12KqA7Usb9p0ZxR8HINkaoPy1Vi3mPCemzcROArBb+Nnz5RWcOAnj3AwwjhOWXKeENnNlPb+Jkwehdn4Fsf4AghWAP2W+SiQ==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: ibm-entitled-registry-credentials
      namespace: ci

